version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env.docker
    volumes:
      - ~/postgres-data:/var/lib/postgresql/data
